USE MIDNIGHTARBITRAGEDB;
GO

TRUNCATE TABLE BRONZE.RAWLISTINGS;
GO

BULK INSERT BRONZE.RAWLISTINGS
FROM 'C:\USERS\SCOTT\DOCUMENTS\USED CARS PROJECT\KAGGLE DATA\ARCHIVE(2)\VEHICLES.CSV'
WITH (
    FORMAT = 'CSV',          -- TELLS SQL TO RESPECT QUOTES (SO COMMAS INSIDE DESCRIPTIONS DON'T BREAK COLUMNS)
    FIRSTROW = 2,            -- SKIPS THE HEADER ROW
    FIELDQUOTE = '"',        
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\N',    
    TABLOCK                  -- LOCKS THE TABLE TO MAXIMIZE INGESTION SPEED
);
GO