CREATE DATABASE MIDNIGHTARBITRAGEDB;
GO
USE MIDNIGHTARBITRAGEDB;
GO
CREATE SCHEMA BRONZE;
GO
CREATE SCHEMA SILVER;
GO
CREATE SCHEMA GOLD;
GO

CREATE TABLE BRONZE.RAWLISTINGS (
    ID NVARCHAR(MAX),
    URL NVARCHAR(MAX),
    REGION NVARCHAR(MAX),
    REGION_URL NVARCHAR(MAX),
    PRICE NVARCHAR(MAX),
    YEAR NVARCHAR(MAX),
    MANUFACTURER NVARCHAR(MAX),
    MODEL NVARCHAR(MAX),
    CONDITION NVARCHAR(MAX),
    CYLINDERS NVARCHAR(MAX),
    FUEL NVARCHAR(MAX),
    ODOMETER NVARCHAR(MAX),
    TITLE_STATUS NVARCHAR(MAX),
    TRANSMISSION NVARCHAR(MAX),
    VIN NVARCHAR(MAX),
    DRIVE NVARCHAR(MAX),
    SIZE NVARCHAR(MAX),
    TYPE NVARCHAR(MAX),
    PAINT_COLOR NVARCHAR(MAX),
    IMAGE_URL NVARCHAR(MAX),
    DESCRIPTION NVARCHAR(MAX),
    COUNTY NVARCHAR(MAX),
    STATE NVARCHAR(MAX),
    LAT NVARCHAR(MAX),
    LONG NVARCHAR(MAX),
    POSTING_DATE NVARCHAR(MAX)
);

-- 1. Drop the table that failed to build correctly
DROP TABLE IF EXISTS silver.DimVehicle;
GO

-- 2. Rebuild it using GROUP BY to guarantee absolute uniqueness
SELECT 
    HASHBYTES('SHA2_256', ISNULL(manufacturer,'') + ISNULL(model,'') + ISNULL(year,'')) AS VehicleKey,
    TRY_CAST(year AS INT) AS VehicleYear,
    UPPER(manufacturer) AS Manufacturer,
    UPPER(model) AS Model,
    MAX(LOWER(type)) AS BodyType 
INTO silver.DimVehicle
FROM bronze.RawListings
WHERE manufacturer IS NOT NULL AND model IS NOT NULL AND year IS NOT NULL
GROUP BY 
    year, 
    manufacturer, 
    model;
GO

ALTER TABLE silver.DimVehicle ALTER COLUMN VehicleKey VARBINARY(32) NOT NULL; GO
ALTER TABLE silver.DimVehicle ADD CONSTRAINT PK_DimVehicle PRIMARY KEY (VehicleKey); GO

drop table SILVER.DIMGEOGRAPHY;
SELECT DISTINCT 
    HASHBYTES('SHA2_256', ISNULL(STATE,'') + ISNULL(REGION,'')) AS GEOKEY,
    UPPER(STATE) AS STATECODE,
    UPPER(REGION) AS REGIONNAME
INTO SILVER.DIMGEOGRAPHY
FROM BRONZE.RAWLISTINGS
WHERE STATE IS NOT NULL;

ALTER TABLE SILVER.DIMGEOGRAPHY ALTER COLUMN GEOKEY VARBINARY(32) NOT NULL;
ALTER TABLE SILVER.DIMGEOGRAPHY ADD CONSTRAINT PK_DIMGEOGRAPHY PRIMARY KEY (GEOKEY);

drop table SILVER.FACTLISTINGS;
SELECT 
    CAST(ID AS BIGINT) AS LISTINGID,
    HASHBYTES('SHA2_256', ISNULL(MANUFACTURER,'') + ISNULL(MODEL,'') + ISNULL(YEAR,'')) AS VEHICLEKEY,
    HASHBYTES('SHA2_256', ISNULL(STATE,'') + ISNULL(REGION,'')) AS GEOKEY,
    TRY_CAST(PRICE AS DECIMAL(10,2)) AS PRICE,
    TRY_CAST(ODOMETER AS INT) AS ODOMETER,
    LOWER(CONDITION) AS CONDITION,
    LOWER(TITLE_STATUS) AS TITLESTATUS,
    -- CRAIGSLIST POSTING DATES HAVE TIMEZONES, WE JUST WANT THE DATE
    CAST(LEFT(POSTING_DATE, 10) AS DATE) AS POSTINGDATE 
INTO SILVER.FACTLISTINGS
FROM BRONZE.RAWLISTINGS
WHERE 
    TRY_CAST(PRICE AS DECIMAL(10,2)) BETWEEN 500 AND 150000 -- FILTER OUT EXTREME OUTLIERS
    AND TRY_CAST(ODOMETER AS INT) < 300000 -- FILTER OUT EXTREME MILEAGE
    AND UPPER(TITLE_STATUS) = 'CLEAN'; -- WE ONLY WANT CLEAN TITLES FOR ARBITRAGE

-- APPLY KEYS
ALTER TABLE SILVER.FACTLISTINGS ALTER COLUMN LISTINGID BIGINT NOT NULL;
ALTER TABLE SILVER.FACTLISTINGS ADD CONSTRAINT PK_FACTLISTINGS PRIMARY KEY (LISTINGID);