CREATE OR ALTER VIEW GOLD.VW_MARKETBASELINES AS
SELECT V.MANUFACTURER,
       V.MODEL,
       V.VEHICLEYEAR,
       COUNT(F.LISTINGID) AS TOTALLISTINGS,
       CAST(AVG(F.PRICE) AS DECIMAL(10,2)) AS AVGMARKETPRICE,
       CAST(AVG(F.ODOMETER) AS INT) AS AVGODOMETER 
FROM SILVER.FACTLISTINGS F
JOIN SILVER.DIMVEHICLE V ON F.VEHICLEKEY = V.VEHICLEKEY
GROUP BY V.MANUFACTURER,
         V.MODEL,
         V.VEHICLEYEAR
HAVING COUNT(F.LISTINGID) > 10;